# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='机房名称')),
                ('bandwidth', models.CharField(blank=True, max_length=32, verbose_name='带宽')),
                ('contact', models.CharField(blank=True, max_length=128, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='手机')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='地址')),
                ('intranet', models.TextField(blank=True, verbose_name='内网')),
                ('extranet', models.TextField(blank=True, verbose_name='外网')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('operator', models.CharField(blank=True, max_length=32, verbose_name='运营商')),
                ('comment', models.TextField(blank=True, verbose_name='描述')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_ip', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='内网IP')),
                ('ex_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='外网IP')),
                ('project_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='项目名称')),
                ('host_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='主机名')),
                ('service_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='服务名')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='位置')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cpu_model', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPU型号')),
                ('cpu_cores', models.IntegerField(blank=True, null=True, verbose_name='CPU核数')),
                ('cpu_count', models.IntegerField(blank=True, null=True, verbose_name='CPU个数')),
                ('mem', models.CharField(blank=True, max_length=255, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, max_length=255, null=True, verbose_name='磁盘')),
                ('os_version', models.CharField(blank=True, max_length=255, null=True, verbose_name='系统版本')),
                ('os_kernel', models.CharField(blank=True, max_length=255, null=True, verbose_name='系统内核')),
                ('status', models.NullBooleanField(default=False, verbose_name='运行状态')),
                ('max_open_files', models.IntegerField(blank=True, null=True, verbose_name='最大打开文件数')),
                ('uptime', models.IntegerField(blank=True, null=True, verbose_name='在线时间（天）')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
        ),
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='资产组名')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('comment', models.TextField(blank=True, verbose_name='描述')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(blank=True, max_length=255, null=True, verbose_name='端口')),
                ('service_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='服务名')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Server', verbose_name='服务器')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='servers', to='cmdb.ServerGroup', verbose_name='资产组'),
        ),
        migrations.AddField(
            model_name='server',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='cmdb.IDC', verbose_name='IDC'),
        ),
    ]
