# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User', verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='server',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User', verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='servergroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User', verbose_name='创建者'),
        ),
    ]
