# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 11:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('majors', models.CharField(max_length=20, null=True, verbose_name='专业')),
                ('worktype', models.CharField(max_length=20, null=True, verbose_name='工作类型')),
                ('contentc', models.CharField(max_length=64, null=True, verbose_name='工作内容')),
                ('datet', models.DateField(default=True, null=True, verbose_name='日期')),
                ('starttime', models.TimeField(default=True, null=True, verbose_name='开始时间')),
                ('lengtime', models.TimeField(default=True, null=True, verbose_name='时间长度')),
                ('networkn', models.CharField(max_length=128, null=True, verbose_name='涉及网元')),
                ('department_name', models.CharField(max_length=64, null=True, verbose_name='工作发起人(部门/名字)')),
                ('head', models.CharField(max_length=20, null=True, verbose_name='互联网室负责人')),
                ('announeoms', models.CharField(max_length=20, null=True, verbose_name='涉及的EOMS公告号')),
                ('singleeoms', models.CharField(max_length=2048, null=True, verbose_name='涉及的EOMS单号')),
                ('enforcer', models.CharField(max_length=20, null=True, verbose_name='工作实施人')),
                ('remark', models.CharField(max_length=20, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': 'excel表格信息',
                'verbose_name': 'excel表格信息',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='./upload/%Y/%m')),
                ('date_t', models.DateTimeField(auto_now_add=True)),
                ('user_u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='谁上传的文件')),
            ],
            options={
                'verbose_name_plural': '上传文件',
                'verbose_name': '上传文件',
            },
        ),
    ]
