# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ssh_command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=200, verbose_name='命令')),
            ],
            options={
                'verbose_name': '命令',
                'verbose_name_plural': '命令',
            },
        ),
        migrations.CreateModel(
            name='ssh_port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='虚拟机名字')),
                ('device_type', models.CharField(max_length=30, verbose_name='板卡')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='链接密码')),
                ('port', models.CharField(max_length=8, verbose_name='端口')),
                ('secret', models.CharField(max_length=20, verbose_name='密匙')),
                ('verbose', models.CharField(default='False', max_length=25, verbose_name='默认')),
            ],
            options={
                'verbose_name': '链接机子的信息',
                'verbose_name_plural': '链接机子的信息',
            },
        ),
        migrations.AddField(
            model_name='ssh_command',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.ssh_port', verbose_name='虚拟机'),
        ),
    ]
