# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'default_permissions': (), 'permissions': (('get_contact', '获取邮件组列表'), ('add_contact', '添加邮件组'), ('edit_contact', '编辑邮件组'), ('del_contact', '删除邮件组')), 'verbose_name': '邮件', 'verbose_name_plural': '邮件'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': (), 'permissions': (('get_project', '获取项目列表'), ('add_project', '添加项目'), ('edit_project', '编辑项目'), ('del_project', '删除项目')), 'verbose_name': '项目详情', 'verbose_name_plural': '项目详情'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='邮件号码'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='邮件名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='列表名'),
        ),
    ]
