# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171108_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='进入管理'),
        ),
    ]
