# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_perm',
            field=models.BooleanField(default=True),
        ),
    ]
